/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Entidades.Jugador;
import Entidades.Planta;
import EstructurasDeDatos.*;
import graphviz.Pintar;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose
 */
public class Inicio extends javax.swing.JFrame {

    public static ListaSimple listaJugador = new ListaSimple();
    public static Cola colaPlantas = new Cola();
    public static Pila pilaZombis = new Pila();
    public static ListaSimple catalogoPlanta = new ListaSimple();
    public static ListaSimple catalogoZombi = new ListaSimple();
    public static FormJugadorPlanta jugadorPlanta;
    public static FormJugadorZombi jugadorZombi;

    /**
     * Creates new form Inicio
     */
    public Inicio() {

        //  Cola cola=new Cola();
        //  for(int i=0;i<20;i++){
        //     cola.agregarACola(i);

        //  }

        // Pila pila=new Pila();
        // for(int i=0;i<20;i++){
        //    pila.apilar(i);

        // }
        //int nu=(int)pila.eliminar();
        // System.out.println(""+nu);
//        for(int i=0;i<20;i++){
//            NodoSimple nodo=cola.primerNodo;
//            System.out.println(""+nodo.datos);
//            nodo=nodo.siguienteNodo;
//        }
        //int nodo=(int)cola.eliminar();
        // System.out.println(""+nodo);
        initComponents();
        setSize(930, 600);
        setTitle("Plantas vs Zombis");



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPlantas = new javax.swing.JButton();
        btnZombis = new javax.swing.JButton();
        btnEmpezar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnCrearPlanta = new javax.swing.JButton();
        btnCrearZombi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPlantas.setText("Plantas");
        btnPlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlantasActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlantas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 120, 60));

        btnZombis.setText("Zombis");
        btnZombis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZombisActionPerformed(evt);
            }
        });
        getContentPane().add(btnZombis, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 110, 60));

        btnEmpezar.setText("Empezar Juego");
        btnEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpezarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmpezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 180, 70));

        btnBorrar.setText("Borrar Datos");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 190, 70));

        btnCrearPlanta.setText("Crear Planta");
        btnCrearPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPlantaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearPlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, -1, -1));

        btnCrearZombi.setText("Crear Zombi");
        btnCrearZombi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearZombiActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearZombi, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, -1, -1));

        jButton1.setText("Ver catalogo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, -1, -1));

        jButton2.setText("Ver catalogo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 530, -1, -1));

        jButton3.setText("Reporte Catalogo Planta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jButton4.setText("Reporte Catalogo Zombi");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoInicio.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlantasActionPerformed

        if (listaJugador.buscarJugador("Planta") == null) {
            Jugador jugador = new Jugador();
            jugador.setTipo("Planta");
            listaJugador.agregarAlFinal(jugador);
        } else {
        }
        jugadorPlanta = new FormJugadorPlanta(this, true);
        jugadorPlanta.setVisible(true);



    }//GEN-LAST:event_btnPlantasActionPerformed

    private void btnEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpezarActionPerformed
        //FormTamanioMatriz matriz = new FormTamanioMatriz(this, true);
        //matriz.setVisible(true);

        Tablero tablero = new Tablero();
        tablero.setVisible(true);
        tablero.setResizable(false);
        setVisible(false);

    }//GEN-LAST:event_btnEmpezarActionPerformed

    private void btnZombisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZombisActionPerformed

        if (listaJugador.buscarJugador("Zombi") == null) {
            Jugador jugador = new Jugador();
            jugador.setTipo("Zombi");
            listaJugador.agregarAlFinal(jugador);
        } else {
        }

        jugadorZombi = new FormJugadorZombi(this, true);
        jugadorZombi.setVisible(true);


    }//GEN-LAST:event_btnZombisActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        listaJugador = new ListaSimple();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnCrearPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPlantaActionPerformed
        FormCrear crearPlanta = new FormCrear(this, true, "Planta");
        crearPlanta.setVisible(true);

    }//GEN-LAST:event_btnCrearPlantaActionPerformed

    private void btnCrearZombiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearZombiActionPerformed
        FormCrear crear = new FormCrear(this, true, "Zombi");
        crear.setVisible(true);

    }//GEN-LAST:event_btnCrearZombiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FormCatalogo catalogo = new FormCatalogo(this, true, "Planta");
        catalogo.setVisible(true);
        catalogo.setBounds(0, 0, 640, 500);
        //catalogo.PanelCatalogo.setLayout(null);
//        FormComponeneteCatalogo componente=new FormComponeneteCatalogo();
//            componente.setVisible(true);
//            componente.setBounds(0,111, 462, 111);
//            catalogo.panelCatalogo.add(componente);
//            
//            FormComponeneteCatalogo componente2=new FormComponeneteCatalogo();
//            componente2.setVisible(true);
//            componente2.setBounds(0,222, 462, 111);
//            catalogo.panelCatalogo.add(componente2);

//        JButton b=new JButton("sdfasdf");
//        b.setBounds(0,0, 100, 100);
//        catalogo.panelCatalogo.add(b);
//        
//                JButton b2=new JButton("sdfasdf");
//        b2.setBounds(0,100, 100, 100);
//        catalogo.panelCatalogo.add(b2);
//        
//        for(int i=0;i<Inicio.catalogoPlanta.tamanioDeLaLista();i++){
//            
//            FormComponeneteCatalogo componente=new FormComponeneteCatalogo();
//            componente.setVisible(true);
//            componente.setBounds(0, i*111, 462, 111);
//            catalogo.panelCatalogo.add(componente);
//            
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FormCatalogo catalogo = new FormCatalogo(this, true, "Zombi");
        catalogo.setVisible(true);
        catalogo.setBounds(0, 0, 680, 500);
        //catalogo.PanelCatalogo.setLayout(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    //String titulo;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (catalogoPlanta.primerNodo != null) {
            Pintar pintar = new Pintar();
            pintar.reporteCatalogoPlanta("Catalogo de Plantas");
            JOptionPane.showMessageDialog(this, "Reporte generado exitosamente!", "", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "El catalogo de plantas esta vacio!", "", JOptionPane.INFORMATION_MESSAGE);
        }

        //generarReporte("Catalogo de Plantas");

        /* String titulo = "";
         String cadena = "";

         String numero = "", nombre = "", ataque = "", vida = "", tipo = "";
         int indice = 1;

         ListaSimple lista = Inicio.catalogoPlanta;
         NodoSimple nodo = lista.primerNodo;

         for (int i = 0; i < lista.tamanioDeLaLista(); i++) {



         Planta planta = (Planta) nodo.datos;

         numero = numero + "|" + Integer.toString(indice);
         nombre = nombre + "|" + planta.getNombre();
         ataque = ataque + "|" + planta.getAtaque();
         vida = vida + "|" + planta.getVida();
         tipo = tipo + "|" + planta.getTipoAtaque();

         indice++;
         // }

         nodo = nodo.siguienteNodo;

         }





         //codigo para grahpiz

         cadena = "digraph tabla {"
         + "node [shape=record];"
         + "Titulo[label=\"Catalogo de Plantas\"];"
         + "node [shape=record];"
         + "Catalogo[label=\""
         + "{No." + numero
         + "}|{Nombre" + nombre
         + "}|{P. Ataque" + ataque
         + "}|{P. Defensa" + vida
         + "}|{Tipo Ataque" + tipo
         + "}\"];Titulo -> Catalogo;}";


         titulo = "Catalogo de Plantas";
         Pintar pintar = new Pintar(titulo, cadena);*/
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (catalogoPlanta.primerNodo != null) {
            Pintar pintar = new Pintar();
            pintar.reporteCatalogoZombi("Catalogo de Zombis");
            JOptionPane.showMessageDialog(this, "Reporte generado exitosamente!", "", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "El catalogo de zombis esta vacio!", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
//        Pintar pintar = new Pintar();
//        pintar.reporteJugadores("Jugadores");
        Tablero tablero = new Tablero();
        tablero.setVisible(true);
        tablero.setResizable(false);
//        JButton b=new JButton();
//        b.setBounds(0,0, 100, 100);
//        tablero.panelPlanta.add(b);
//        
//        JButton b2=new JButton();
//        b2.setBounds(0,100, 100, 100);
//        tablero.panelPlanta.add(b2);

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCrearPlanta;
    private javax.swing.JButton btnCrearZombi;
    private javax.swing.JButton btnEmpezar;
    private javax.swing.JButton btnPlantas;
    private javax.swing.JButton btnZombis;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
